### ISSUE TITLE
How can I get the instance of MyMenuTableViewController?

### ISSUE THREAD

**Issue by eduardobonfa** [evnaz/ENSwiftSideMenu#101]
I created a delegate in MyMenuTableViewController and I want to execute it in ViewController. But how do I get the instance to execute the delegate in View Controller?

**Comment by hopye** [comment]
if you have found the answer to this, please let me know

**Comment by evnaz** [comment]
Hi, 
Now you can use ```self.sideMenuController()?.sideMenu?.menuViewController``` to access to side menu content view controller
