### ISSUE TITLE
How to push controller from side menu

### ISSUE THREAD

**Issue by sahabe1** [evnaz/ENSwiftSideMenu#110]
Can I push controller from side menu and then back from pushed controller  then open side menu

**Comment by evnaz** [comment]
use  ```sideMenuController()?.setContentViewController(destViewController)``` when user select a cell.
see example project

**Comment by sahabe1** [comment]
it just set the controller and  when swipe on view controller then menu open 
I want to show default back button when click on some indexpath on side menu

**Comment by evnaz** [comment]
ok. try to use ```sideMenuController().pushViewController(controller)```

**Comment by sahabe1** [comment]
its throwing error Value of type 'ENSideMenuProtocol' has no member 'pushViewController'

**Comment by evnaz** [comment]
because you have to cast
```let navController = sideMenuController() as! UINavigationController
        navController.pushViewController(destViewController, animated: true)```

**Comment by sahabe1** [comment]
thanks evnaz

**Comment by prashanthilucky** [comment]
push from sidemenu controller to new controller is working. but we swipe leftside in newcontroller sidememnu is opening.

**Comment by prashanthilucky** [comment]
In one controller am using side menu,  from that controller am giving push to new controller. in new controller back button is working, but if swipe from left side in new controller side menu is opening.
