### ISSUE TITLE
slide gesture booleans not working appropriately

### ISSUE THREAD

**Issue by bass4aj** [evnaz/ENSwiftSideMenu#112]
I have been trying to disable the menu on certain view controllers by returning false on
         func sideMenuShouldOpenSideMenu() -> Bool. 
If I try to swipe the menu open multiple times, it will begin working. 

Additionally, if I disable the swipe gestures in EnSideMenu.swift, (set booleans to false), trying a combination of swipes and toggling from the menu button will cause the menu to work from swipes.

No specific combination of toggle button and gestures seem to cause the break.

These issues are easily recreated in the provided example project.

**Comment by evnaz** [comment]
Thanks for the report!

**Comment by NoteVote** [comment]
Thanks for the quick reply! Works great! Side question, since I am not sure if it warrants its own issue, is there a way to have the menu behind the navigation bar when using navigation bar objects separate from the navigation controller?

**Comment by evnaz** [comment]
just use ```bringSubviewToFront``` func
