### ISSUE TITLE
How to show/disable sidemenu based on current screen?

### ISSUE THREAD

**Issue by younanjo** [evnaz/ENSwiftSideMenu#122]
Hi guys,

How can i disable ENSwiftSideMenu from being shown (dragged in from the edge) if they're on a given screen? For example i don't want to show the sidemenu on login screen but other screens user can use the sidemenu. Any ideas?

**Comment by evnaz** [comment]
Hi,
use function ```sideMenuShouldOpenSideMenu ()``` from  ```ENSideMenuDelegate```
to set your VC as a delegate of side menu use:
```swift 
self.sideMenuController()?.sideMenu?.delegate = self
```

**Comment by younanjo** [comment]
Thanks @evnaz 

I tired that, I've added

```
class ViewController: UIViewController, ENSideMenuDelegate {
....
override func viewDidLoad() {
        super.viewDidLoad()

        self.sideMenuController()?.sideMenu?.delegate = self
      ...
}

    func sideMenuShouldOpenSideMenu() -> Bool {
         print("sideMenuShouldOpenSideMenu")
        return false
    }
    
}
```

the function is getting called (sideMenuShouldOpenSideMenu) but i can still slide from left to see the menu! Any suggestions?

**Comment by evnaz** [comment]
Does menu opens by ```toggleMenu()```?

**Comment by younanjo** [comment]
@evnaz  I can see some inconsistent behaviour. I noticed that "resume" was printed where i was sliding so that's coming from 

```
extension ENSideMenu: UIDynamicAnimatorDelegate {
    public func dynamicAnimatorDidPause(animator: UIDynamicAnimator) {
        if (self.isMenuOpen) {
            self.delegate?.sideMenuDidOpen?()
        } else {
            self.delegate?.sideMenuDidClose?()
        }
    }
    
    public func dynamicAnimatorWillResume(animator: UIDynamicAnimator) {
        print("resume")
    }
}
```

If i keep trying to slide, sometimes the side menu does not open and that's when i don't see "resume". but when it does slide i can see the word "resume" printed.
