### ISSUE TITLE
Hide menu when tapping outside

### ISSUE THREAD

**Issue by zishanj** [evnaz/ENSwiftSideMenu#128]
How can I hide menu while tapping outside the menu area?

**Comment by LOVE-2-CODE** [comment]
+1

**Comment by yatch999** [comment]
https://github.com/evnaz/ENSwiftSideMenu/issues/75

This thread is helpful.
If you need I may give my sample code.

**Comment by zishanj** [comment]
@yatch999 Thanks for sharing the link. I have tried the solution mentioned on that link but it's bit buggy. Sometimes the main view controller get completely disabled and I can't tap on items on it until I show/hide the menu again.

Can you share your working code please?

**Comment by zishanj** [comment]
@yatch999 Thanks for sharing the link. That solution works perfectly.
