### ISSUE TITLE
Side Menu Won't Collapse When Click Current Menu Item

### ISSUE THREAD

**Issue by XinwenCheng** [evnaz/ENSwiftSideMenu#147]
Hi @evnaz ,

When I click the current menu item, how can I make the side menu collapse automatically?

Thanks!

**Comment by XinwenCheng** [comment]
OK, I got it. Need to use following code by myself.
```
self.sideMenuController()?.sideMenu?.hideSideMenu()
```

**Comment by amjad401** [comment]
Where did you put this code?
I need this

**Comment by XinwenCheng** [comment]
To instance an ENSideMenu like following,
```
sideMenu = ENSideMenu(sourceView: self.view, menuViewController: LeftSideNavigationMenuViewController(), menuPosition: .Left)
```
There's LeftSideNavigationMenuViewController which contains table view of navigation items, and in its override func tableView(tableView: UITableView, didSelectRowAtIndexPath indexPath: NSIndexPath) function, I put following code,
```
if indexPath.row == selectedMenuItem {
    self.sideMenuController()?.sideMenu?.hideSideMenu()

    return
}
```
Hope this helps!

**Comment by amjad401** [comment]
Thank you very much!!
