### ISSUE TITLE
a new viewcontroller instance is made

### ISSUE THREAD

**Issue by wizmeister** [evnaz/ENSwiftSideMenu#35]
first of all, great work!!!

I am looking for a way for the menu to pop a previously visited view controller at it's latest state, not to instantiate a new one... any tips?

**Comment by sunny596** [comment]
@wizmeister did you have any luck with this ?
As douglasd3 mentioned, how to create and instance the view controller in App Delegate ?
And, where does the above code go ?
Sorry I am a noob. Still trying to understand how things work.
Thanks in advance !

**Comment by evnaz** [comment]
You can create a singleton instance of your view controller or store your view controller in a property in the menu TVC.

**Comment by douglasd3** [comment]
The code goes on the table view controller of the menu, in the tableViewControllerDidSelectRow method, take a look at the example code and you will know what i'm talking about :)

To create the instance of your mainviewController in your app delegate:
In your App Delegate just add:

//Your main view controller
 var mainViewController: UIViewController?

In your main view controller's viewDidLoad just do something like this:

       var app = UIApplication.sharedApplication()
        
        if let delegate = app.delegate as? AppDelegate{
            
            delegate.mainViewController = self
        }

You can also create a singleton like evnaz said.

Hope it helped :)

**Comment by wizmeister** [comment]
On your App Delegate, create an optional property for each of your view Controllers
e.g.

 
`var firstViewController: UIViewController?`

on your View Controllers ViewDidLoad method, add:

    var app = UIApplication.sharedApplication()
    if let delegate = app.delegate as? AppDelegate{
    delegate.firstViewController = self
    }

then, on the menu's tableviewcontroller, right before switch indexPath.row add:
`var app = UIApplication.sharedApplication()`

and then on each indexPath.row case do as such:

    if let delegate = app.delegate as? AppDelegate {
                
                if let mainController = delegate.firstViewController {
                    
                    destViewController =  delegate.firstViewController!
                }
                else{
                    destViewController = mainStoryboard.instantiateViewControllerWithIdentifier("firstViewController") as UIViewController
                    
                }
            } else {
            
            destViewController = mainStoryboard.instantiateViewControllerWithIdentifier("firstViewController") as UIViewController
            }
            break

**Comment by sunny596** [comment]
Hello everyone.

Thanks a lot for your help. I could follow @wizmeister code perfectly!
Though it gives an error after the same view is called back from the menu :(

Here is the error -
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Pushing the same view controller instance more than once is not supported (<Test.FirstLocationViewController: 0x7bf21ae0>)

**Comment by wizmeister** [comment]
You have probably done something wrong... Did you miss any bracket? Or did you double type the pushviewcontroller on your menu's tableViewController file?

**Comment by sunny596** [comment]
Hi @wizmeister,

One thing I can think of is that my optional property name and the view controller class name is the same.
var firstViewController: UIViewController?
and firstViewController is also the class of my view controller (of type UIViewController).

Could this be a problem ? Would it create clashes ? 
I will try to change names when I get home from work and double check if I have made any duplicate calls.

**Comment by wizmeister** [comment]
No in my example all my ViewControllers are of class UIViewController, this is normal as you are subclassing UIViewController. It should work.

Kind of weird though, try making a new clean project, download the control again, to start fresh and see if there is something wrong with your current project by comparing.
