### ISSUE TITLE
Disable Menu?

### ISSUE THREAD

**Issue by KyleMassacre** [evnaz/ENSwiftSideMenu#38]
Is there a simple way to disable the menu on a particular view controller? Sorry if it sounds n00bish but I am :blush:

**Comment by Bautistax** [comment]
the bar button menu? or the menu side bar itself ?

**Comment by KyleMassacre** [comment]
Sorry, the entire menu itself, you see I have a login/authentication view controller which requires them to login to access the app so I don't really want them to have the menu visible to them

**Comment by venom889** [comment]
I am currently doing this using the ENSideMenuDelegate's method sideMenuWillOpen() and the sideMenu's hideSideMenu() method. It would however be a much better idea to add a disable flag to the implementation.

**Comment by evnaz** [comment]
Hi @venom889,
Yes, it should be in the ENSideMenuDelegate. I'm going to add it to the lib soon.

**Comment by tawrahim** [comment]
@venom889 do you mind sharing a gist of how you did it?

**Comment by evnaz** [comment]
Just added this option to the lib. 
Set your view controller delegate of ENSideMenu in viewDidLoad or viewWillAppear:
```swift
self.sideMenuController()?.sideMenu?.delegate = self;
```
and implement this function
```swift
func sideMenuShouldOpenSideMenu() -> Bool {
        return false;
}
```
