### ISSUE TITLE
Can I use with Obj-C?

### ISSUE THREAD

**Issue by Pokotuz** [evnaz/ENSwiftSideMenu#39]
Im trying to use with my objc project but have a problem with calling

sideMenu = ENSideMenu(sourceView: self.view, menuTableViewController: MyMenuTableViewController(), menuPosition:.Left)

Any suggestion?

Very cool sidemenu.
Thank you very very much.

**Comment by evnaz** [comment]
Hi @Pokotuz 
Yes it is possible. Check ObjCExample project. I just added it to the repo.

**Comment by Pokotuz** [comment]
Very thx to your kindness.

... And a little questions, How do I bring the menu on top of navigation bar?
And blur effect in ObjSampleProject is disappear, its normal right?

**Comment by evnaz** [comment]
To bring menu on top, search in the project for 'bringSubviewToFront(navigationBar)' and comment it, it should be outside of the lib.
Blur effect should work, i will check it soon.

**Comment by Pokotuz** [comment]
OK I got it, Thank you.
