### ISSUE TITLE
Problem with set content

### ISSUE THREAD

**Issue by lostpupil** [evnaz/ENSwiftSideMenu#40]
![image](https://cloud.githubusercontent.com/assets/2015695/5752816/c26da9d6-9cb8-11e4-9a86-f10863fb21b3.png)
Here is my storyboard, these two red mark show the view that I used for side menu. And this is my dir
![image](https://cloud.githubusercontent.com/assets/2015695/5752832/02712ecc-9cb9-11e4-8c3c-46975d947009.png)
My code looks fine, but I don't know why I can not set ContentView
![image](https://cloud.githubusercontent.com/assets/2015695/5752835/2742c3f0-9cb9-11e4-9b90-512eeb639b1d.png)
which I click the sidebar item, nothing happened to second view controller

**Comment by lostpupil** [comment]
Well I realize that was I am using both tab layout and navigation controller, which confused me very much, how do I use both tab bar and sidebar?

**Comment by ejpusa** [comment]
The tab bar and side bar are really 2 different entities. There is no conflict at all. 

Think you need something like this as your last line:
    presentViewController(destinationViewController, animated: true, completion: nil)

**Comment by PierreBrisorgueil** [comment]
same problem, did you find a solution?

**Comment by PierreBrisorgueil** [comment]
Same problem, did you find a solution ? 

presentViewController(destinationViewController, animated: true, completion: nil)

not  really a good idea i think, we loose self.pushViewController .... so the Navigation Bar

I am blocked to make it worked with a tab bar controller, if somebody has an example !

**Comment by lostpupil** [comment]
@PierreBrisorgueil I did find a solution here. Maybe you can contact me via banana@eurus.cn.

**Comment by PierreBrisorgueil** [comment]
@lostpupil Ok thx, i solved my problem with SWRevealViewController, but i will send you a mail. 
I will be happy to understand and offer a sample for this with ENSwiftSideMenu on GitHub if you are agree.

**Comment by vimalsaifudin** [comment]
Same problem.. Can anyone please post a solution for this ? @lostpupil ?

**Comment by PierreBrisorgueil** [comment]
no solution for me, just try SWRevealViewController, it will take 15 min max @vimalsaifudin
