### ISSUE TITLE
swift 1.2

### ISSUE THREAD

**Issue by FabianTerhorst** [evnaz/ENSwiftSideMenu#43]
Hello,

i have tried today to run my project on the new xcode 6.3 beta with swift 1.2, but i have seen that your project isn´t compatible with this swift version. My question is when you want to adapt your project to swift 1.2.

**Comment by ejpusa** [comment]
Hi, same problem here. Updates would be great.

**Comment by evnaz** [comment]
just pushed a new branch with swift 1.2 support

**Comment by ejpusa** [comment]
Awesome, thanks! :-)
