### ISSUE TITLE
How to reduce the duration of animation while bouncing is enabled

### ISSUE THREAD

**Issue by ashumishra224** [evnaz/ENSwiftSideMenu#46]
Hello Evnaz!
Hope you are doing good.
I have integrated your controller in my project but I want to reduce  the duration of animation while opening side menu. How  can I do it in togglemenu where you have integrated UIDynamics Behaviour?

**Comment by ejpusa** [comment]
Almost all your tweeks happen in ENSideMenu.swift. You'll set a bunch of numbers there effecting the physics of the menu. Make your changes and you'll be able to see the results on the spot. You can get zillions of permutations. And experimenting is fun. :-)
