### ISSUE TITLE
Cocoapods

### ISSUE THREAD

**Issue by ivangodfather** [evnaz/ENSwiftSideMenu#48]
Will be available in Cocoapods?  :-)

**Comment by ivangodfather** [comment]
How can i use it with cocoapods?
 I found this: 
https://github.com/CocoaPods/Specs/blob/master/Specs/ENSwiftSideMenu/0.0.3/ENSwiftSideMenu.podspec.json
When i import "import EnSwiftSideMenu"
Then i have no access to the classes since they are not public, like ENSideMenuNavigationController...

**Comment by evnaz** [comment]
Added latest version to cocopods.
to import the library use:
```
import ENSwiftSideMenu
```
