### ISSUE TITLE
Disabling swipe right while allowing toggle of menu through button

### ISSUE THREAD

**Issue by Naoto-Ida** [evnaz/ENSwiftSideMenu#52]
I'm still a bit unsure about how to do this with Swift,
and wondering if writing this would be a valid PR.
Any suggestions?

**Comment by evnaz** [comment]
Use allowLeftSwipe and allowRightSwipe properties of sideMenu to enable or disable gestures.

**Comment by Naoto-Ida** [comment]
@evnaz Thanks!

**Comment by Naoto-Ida** [comment]
@evnaz 
sorry, how would i use that property?

**Comment by evnaz** [comment]
you can use next line in the NavigationViewController's viewDidLoad function:
```
sideMenu?.allowRightSwipe = false
```
or from any content view controller:
```
self.sideMenuController()?.sideMenu?.allowLeftSwipe = false;
```
by default this values is true

**Comment by Naoto-Ida** [comment]
Thank you so much, I'll try this out!

**Comment by Naoto-Ida** [comment]
@evnaz Hi, there seems to be no member named "AllowRightSwipe" in"ENSideMenu"...

**Comment by Naoto-Ida** [comment]
@evnaz Oh, I'm sorry, I just checked the code in the example and source, and the sample one seemed to be lacking the "AllowRightSwipe" member. Thank you so much!
