### ISSUE TITLE
height of menu if orientation is changed

### ISSUE THREAD

**Issue by simonsiedler** [evnaz/ENSwiftSideMenu#57]
Great work, I really enjoy the menu!
However I have a small problem if the menu is open and the orientation is changed from portrait to landscape. The menu position works fine, but the scrolling of the menu is not enabled if there are a lot of entries. To reproduce this just create a menu with 10 or more entries, so that not all are directly visible in landscape mode.
I tried to change the height of the sidemenu tableview, but couldn't quite get a working soltion since I am pretty new to mobile programming.
Hope someone has a suggestion to solve this problem.
Keep up the good work

**Comment by animaonline** [comment]
I'm having the same problem, any updates?

**Comment by dexterliu1214** [comment]
```
override func viewDidLayoutSubviews() {
  fixSideMenuSize()
  super.viewDidLayoutSubviews()
}
```

add this to your view controller

**Comment by simonsiedler** [comment]
Thank you very much, that solved the problem!

**Comment by djdance** [comment]
also add into func updateFrame()

`        guard (outterView != nil) else {
            return
        }
        let bgFrame = CGRect(
            x: 0,
            y: 0,
            width: width,
            height: height
        )
        outterView.frame = bgFrame
`
