### ISSUE TITLE
Turning off the menu in some view controllers

### ISSUE THREAD

**Issue by amjohnno** [evnaz/ENSwiftSideMenu#62]
I'm having unexpected results with the menu, though perhaps this has to do with me being new to coding than anything else. I expected to only have the menu appear in certain view controllers - those I made delegates of the menu. This would just be those view controllers actually listed in the menu, and not subsequent view controllers segued to. However, this does not seem to be the case as the menu is always accessible when swiping from the left edge of the screen.

Is there any way to turn off the menu in certain view controllers?

**Comment by evnaz** [comment]
Hi @amjohnno ,
Set the view controller as a delegate of side menu in viewWillAppear function
```
self.sideMenuController()?.sideMenu?.delegate = self
```
and implement next function
```
func sideMenuShouldOpenSideMenu() -> Bool {
        return false
    }
```

**Comment by amjohnno** [comment]
Hi @evnaz. That worked perfectly. Thank you for your help. And for the menu!
