### ISSUE TITLE
Menu will not reopen following unwinding from a view controller where sideMenuShouldOpenSideMenu() is false

### ISSUE THREAD

**Issue by amjohnno** [evnaz/ENSwiftSideMenu#63]
Thank you for your answer to my question regarding sideMenuShouldOpenSideMenu() a few days ago, but I now seem to be having further issues.

ViewController1 has sideMenuShouldOpenSideMenu() set to true.
ViewController2 has sideMenuShouldOpenSideMenu() set to false.

It works fine until I unwind from ViewController2 to ViewController1. sideMenuShouldOpenSideMenu(), it seems, continues to be set to false, as the menu will no longer open in ViewController1. I am assuming that is because sideMenuShouldOpenSideMenu() is not being called upon return. Is there a way around this?

Edit: It seems that this is sporadic and only happens when I unwind a segue from within a UIAlert. I can't imagine what the issue could be.

**Comment by evnaz** [comment]
Perhaps, the delegate of side menu is set to wrong view controller. You need to assign delegate to proper view controller on switch view controllers.

**Comment by amjohnno** [comment]
Sorted. I moved ```self.sideMenuController()?.sideMenu?.delegate = self``` to ```viewDidAppear``` instead of ```viewDidLoad```. Seems obvious now! Thanks for the help.
