### ISSUE TITLE
Is there a built-in way to programatically switch between menu items?

### ISSUE THREAD

**Issue by albertkim** [evnaz/ENSwiftSideMenu#69]
For example, if a user goes to a menu item, and the app determines that the user has not logged in, then it should redirect to the login tab.

The only way I know to do this is by using self.sideMenuController()?.setContentViewController, but that doesn't change the selected menu index. I'm wondering if there's some handy method around that i missed.

**Comment by evnaz** [comment]
Hi,
There is no such possibility in the lib

**Comment by ejpusa** [comment]
I do something like this with Instagram and OAuthSwift. 

If you are not logged into the 'Gram, you can a login screen by way of OAuth2, then the main sidebar appears if u login. I allow users to skip the login, but do bug them each time they re/start the App. IG just throttles u down to 5,000 requests per hour. So you want all your users to have their own AccessToken.

OAuthSwift things here: (this is a popular one, there others, and it is a bit tricky to get it all to work)
https://github.com/dongri/OAuthSwift
