### ISSUE TITLE
Slider menu animation behaviour need to change little

### ISSUE THREAD

**Issue by imrielruchi** [evnaz/ENSwiftSideMenu#70]
Hi,

This is a nice example for slider menu.

I need some change in animation behaviour. it should be like parentview will be slide when sliderview open instead of overlapping sliderview on parentview.

I need the same behaviour of slidermenu just like facebook app have . 

Any help will be more appreciate.

Thanks.

**Comment by evnaz** [comment]
Hi,
Unfortunately there is no way to make such behavior. The basis of this control is UINavigationController with default logic to set content view controller. You need to look some another control with UIViewController as a root view controller. For example this one https://github.com/romaonthego/RESideMenu
