### ISSUE TITLE
Added menu icon instead of text but crashing!

### ISSUE THREAD

**Issue by robomotic** [evnaz/ENSwiftSideMenu#74]
Hello guys, 
I have attempted to add a menu icon instead of the text.
https://github.com/robomotic/ENSwiftSideMenu/tree/MenuIcon
If you go to ViewController2 you will see the menu bar in a ugly blue color but when you press the app is crashing!
The error is quite generic:
[SwiftSideMenu.MyNavigationController toggleMenu]: unrecognized selector sent to instance 0x7fad72828650
And I can't see why is doing that.
Any help ?!?!?!

**Comment by evnaz** [comment]
Hi @robomotic ,
In your fork you have modified the Library/ENSideMenuNavigationController.swift file. The problem is in that changes. Check the target of the bar button.
