### ISSUE TITLE
Tab bar controller->navigation controller

### ISSUE THREAD

**Issue by devkerby** [evnaz/ENSwiftSideMenu#79]
Can't switch the views when using tab bar controller.
The root controller is tab bar controller. Here is my storyboard:
￼
![image](https://cloud.githubusercontent.com/assets/1308985/8586558/9b213ca0-2622-11e5-8597-0018fafa3c72.png)

￼

￼

**Comment by evnaz** [comment]
Thanks for the report! The update should resolve the issue.
