### ISSUE TITLE
navigationController.popViewControllerAnimated does not work?

### ISSUE THREAD

**Issue by dsun29** [evnaz/ENSwiftSideMenu#83]
I use following code to come back to ViewController B to A, but it doesn't work

```swift
self.navigationController!.popViewControllerAnimated(true)
```
The code below was used to switch from A to B:
```swift
 let storyBoard : UIStoryboard = UIStoryboard(name: "Main", bundle:nil)
            
 let nextViewController = storyBoard.instantiateViewControllerWithIdentifier("B") as! B
            
 sideMenuController()?.setContentViewController(nextViewController)
 ```

**Comment by evnaz** [comment]
Hi,
Seems there is only one view controller in the navigation stack. You need to push view controller first, then you can perform ```popViewControllerAnimated```

**Comment by dsun29** [comment]
Thank you evnaz for your help!
