### ISSUE TITLE
Problem with SideMenu height on orientation change - Tablet

### ISSUE THREAD

**Issue by jeroenbb** [evnaz/ENSwiftSideMenu#88]
Please follow the following steps to reproduce the problem:

1. Set emulator on iPad 2
2. Put the emulator on landscape mode
3. Start your application with the ENSideMenu code
4. Open menu, everything looks okay
5. Put the emulator on portrait mode, menu height doesn't reach end of frame

How can you make the ENSideMenu frame height larger?

**Comment by jeroenbb** [comment]
Found the solution in the closed issues

add the following code in your viewcontrollers

override func viewDidLayoutSubviews() {
        fixSideMenuSize()
        super.viewDidLayoutSubviews()
}

**Comment by djdance** [comment]
thank you man, it works
but this is tooo slowly for me, strange...
