### ISSUE TITLE
the view having a Shadow

### ISSUE THREAD

**Issue by dowhilenet** [evnaz/ENSwiftSideMenu#89]
I set 

`sideMenu?.menuWidth = 80.0 `

<img width="320" alt="qq20150807-1 2x" src="https://cloud.githubusercontent.com/assets/10379476/9139293/fbdd2a04-3d5b-11e5-91d6-902a72c0c341.png">

**Comment by timgerdes93** [comment]
You have to set the value in the ENSideMenu.swift at line 118 (position in my code) although to 80
