### ISSUE TITLE
Compatibility with iOS9

### ISSUE THREAD

**Issue by gyifr** [evnaz/ENSwiftSideMenu#96]
The component does not work with iOS9 and XCode 7, there are some compiling errors. 
Thank you

**Comment by kajensen** [comment]
Yeah, the project needs some modifications to update to swift 2
1. "[.FlexibleHeight, .FlexibleWidth]" in a couple places
2.  change the do while loop to "repeat" while

**Comment by evnaz** [comment]
Hi,
Just updated the lib for ios 9 compatibility

**Comment by gyifr** [comment]
Thank you very much!
